/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import metier.RequeteDeliver2i;
import io.InstanceReader;
import io.exception.ReaderException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import modele.Instance;

/**
 *
 * @author cyril
 */
public class ImportInstance extends javax.swing.JDialog {

    private RequeteDeliver2i requeteDeliver2i;
    
    private EntityManager em;
    
    /**
     * Creates new form ImportInstance
     */
    public ImportInstance(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.em = ((Accueil)parent).getEm();
        
        initComponents();
        initialisationFenetre();
        initConnexion();
    }
    
    private void initialisationFenetre() {
        this.setVisible(true); // Rendre visible
        this.setSize(570, 600); // Défini la taille
        this.setLocationRelativeTo(null); // Centre la fenêtre
        this.getContentPane().setBackground(new Color(255, 227, 171));
        this.setTitle("Deliver2i");
    }
    
    private void initConnexion(){
        try {
            this.requeteDeliver2i = RequeteDeliver2i.getInstance();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex,"ClassNotFoundException",JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex,"SQLException",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importInstanceButton = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        importInstanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importInstanceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(importInstanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(importInstanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importInstanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importInstanceButtonActionPerformed
        int result = importInstanceButton.getApproveButtonMnemonic();
        System.out.println("result :"+result);
        switch (result) {
            case JFileChooser.APPROVE_OPTION:
            String selectedFile = importInstanceButton.getSelectedFile().getAbsolutePath();
            try {
                InstanceReader instanceReader = new InstanceReader(selectedFile);
                Instance inst = instanceReader.readInstance();

                final EntityTransaction et = em.getTransaction();
                
                et.begin();
                em.persist(inst);
                et.commit();
                
            } catch (ReaderException ex) {
                Logger.getLogger(ImportInstance.class.getName()).log(Level.SEVERE, null, ex);//erreur fichier
            }
            this.dispose();
            break;
            case JFileChooser.CANCEL_OPTION:
            System.out.println("Cancel or the close-dialog icon was clicked");
            break;
            case JFileChooser.ERROR_OPTION:
            System.out.println("Error");
            break;
            default:
            System.out.println("app.ImportInstance.importInstanceButtonMouseClicked()");
        }
    }//GEN-LAST:event_importInstanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportInstance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImportInstance dialog = new ImportInstance(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser importInstanceButton;
    // End of variables declaration//GEN-END:variables
}
